# Baserow API Configuration
# Replace with your actual Baserow API token and table IDs
baserow_api_token = "YOUR_BASEROW_API_TOKEN"
votes_table_id = "YOUR_VOTES_TABLE_ID"
options_table_id = "YOUR_OPTIONS_TABLE_ID"
responses_table_id = "YOUR_RESPONSES_TABLE_ID" 